# probit and logistic links

# Pr(Y=1|X) = exp(x)/(1+exp(x)) # cumulative logistic distribution 
# Pr(Y=1|X) = Pho(x) # cumulative normal distribution

# logit is more popular in health sciences since coefficients can be interpreted in terms of odds ratios
# x = ln(p/(1-p))

x = seq(-10, 10, 0.1)

cdf.logit = exp(x) / (1+exp(x))
cdf.probit = pnorm(x, mean = 0, sd = 1)

plot(x, cdf.logit, col = "blue", type = "l")
lines(x, cdf.probit, col = "red")

dens.logit = dlogis(x, location = 0, scale = 1)
dens.probit = dnorm(x, mean = 0, sd = 1)

plot(x, dens.logit, col = "blue", type = "l", xlim = c(-6, 6))
# logistic distribution is symmetric, and is pretty much a normal distribution with some standard deviation
# so it is straight forward to approximate a logistic by a normal, or the reverse
mean(dens.logit)
sd(dens.logit)

plot(x, dens.logit, col = "blue", type = "l", ylim = c(0, 0.5))
lines(x, dens.probit, col = "red")

# more comparisons on fit reasults, likelihood and parameters et al.
set.seed(1)
diff.links = do.call(rbind, lapply(1:1e3, function(i) {
  x = rnorm(1000)
  y = rbinom(n=1000, size=1, prob=pnorm(x))
  logitModel  = glm(y~x, family=binomial(link="logit"))
  probitModel = glm(y~x, family=binomial(link="probit"))
  data.frame(logit = deviance(logitModel), probit = deviance(probitModel))
}))
  
# model fit (deviance) are very similar
plot(diff.links$logit, diff.links$probit)
# model fit by the probit link is better than the logistic link in 33.4% of the times although data were generated by probit model
mean(diff.links$probit - diff.links$logit > 0)

# Compare Stan performance using ADSP data
library(rstan)
setwd("~/GitHub/Genetics/rstan/")
logit = stan_model("logit.stan") # Stan manual
logit2 = stan_model("logit2.stan") # modified version
probit = stan_model("probit.stan") # Stan manual
probit2 = stan_model("probit2.stan") # modified version 

load("mdata.rdt") # ADSP
dat <- list(N = 570, K = 4, D = 2, x = mdata[c("Age", "Sex")], y = as.numeric(mdata$AD1))

logit.mle = optimizing(logit, data = dat)
logit2.mle = optimizing(logit2, data = dat)
probit.mle = optimizing(probit, data = dat)
probit2.mle = optimizing(probit2, data = dat)

logit.mc = sampling(logit, data = dat, chain = 1, iter = 1200, warmup = 200)
probit.mc = sampling(probit, data = dat, chain = 1, iter = 1200, warmup = 200)
probit2.mc = sampling(probit2, data = dat, chain = 1, iter = 1200, warmup = 200)
